import type {
  CplVendorCount,
  DailyReport,
  FailureDetailRow,
  GrowthItem,
  SectionResult,
  SyncHealthRow,
  VendorApiHealthRow,
} from './daily-report';

const NAVY = '#1B2A4A';
const MUTED = '#6B7280';
const GREEN = '#16A34A';
const AMBER = '#F59E0B';
const RED = '#DC2626';
const BORDER = '#E5E7EB';

export function formatPacific(date: Date | null, options?: Intl.DateTimeFormatOptions): string {
  if (!date) return '—';
  return new Intl.DateTimeFormat('en-US', {
    timeZone: 'America/Los_Angeles',
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    timeZoneName: 'short',
    ...options,
  }).format(date);
}

export function renderDailyReportHtml(report: DailyReport): string {
  const dashboardUrl = `${(process.env.NEXT_PUBLIC_APP_URL ?? 'https://td-hub.pctitle.com').replace(/\/$/, '')}/admin/ops`;
  const statusColor = report.summary.status === 'critical' ? RED : report.summary.status === 'attention' ? AMBER : GREEN;

  return `<!doctype html>
<html>
<body style="margin:0;background:#F3F4F6;font-family:Arial,sans-serif;color:#111827;">
  <div style="max-width:700px;margin:0 auto;background:#FFFFFF;">
    <div style="background:${NAVY};color:#FFFFFF;padding:24px;">
      <h1 style="margin:0;font-size:22px;">TD Hub Daily Operations Report</h1>
      <p style="margin:8px 0 0;font-size:13px;color:#D1D5DB;">Generated ${escapeHtml(formatPacific(report.generatedAt))}</p>
      <p style="margin:4px 0 0;font-size:13px;color:#D1D5DB;">Window ${escapeHtml(formatPacific(report.windowStart))} to ${escapeHtml(formatPacific(report.windowEnd))}</p>
    </div>
    <div style="padding:20px 24px;border-bottom:1px solid ${BORDER};">
      <a href="${escapeAttr(dashboardUrl)}" style="color:${NAVY};font-weight:700;text-decoration:none;">View live dashboard</a>
      <div style="margin-top:16px;padding:16px;border:1px solid ${BORDER};border-left:6px solid ${statusColor};border-radius:6px;">
        <div style="font-size:20px;font-weight:700;color:${statusColor};">${report.summary.statusEmoji} ${escapeHtml(titleCase(report.summary.status))}</div>
        <p style="margin:8px 0 0;color:${MUTED};font-size:13px;">Orders synced: <strong>${report.summary.totalOrdersSynced}</strong> · Prelims analyzed: <strong>${report.summary.totalPrelimsAnalyzed}</strong> · Sections loaded: <strong>${report.sectionsLoaded}/13</strong></p>
      </div>
    </div>
    <div style="padding:0 24px 24px;">
      ${renderAttentionHtml(report.summary.attentionItems)}
      ${renderSectionHtml('1. Order Flow (24h)', report.orderFlow, (d) => `
        ${metricGrid([
          ['Synced from SoftPro', d.syncedFromSoftPro],
          ['Created in TD Hub', d.createdInTdHub],
          ['Enriched fully', d.enrichedFully],
          ['Pending enrichment within cooldown', d.pendingEnrichmentWithinCooldown],
          ['Stuck > 6 hours', d.stuckOver6Hours],
        ])}
      `)}
      ${renderSectionHtml('2. Sync Health (24h)', report.syncHealth, (d) => renderSyncRows(d.rows))}
      ${renderSectionHtml('3. Prelims (24h)', report.prelims, (d) => metricGrid([
        ['Fetched', d.fetched],
        ['TESSA analyses queued', d.tessaAnalysesQueued],
        ['TESSA analyses completed', d.tessaAnalysesCompleted],
        ['TESSA analyses failed', d.tessaAnalysesFailed],
        ['Approx. Claude API cost', formatCost(d.approximateClaudeApiCost)],
      ]))}
      ${renderSectionHtml('4. CPLs (24h)', report.cpls, (d) => `
        <p style="margin:0 0 10px;color:${MUTED};font-size:13px;">Generated CPL documents: <strong>${d.generatedDocuments}</strong></p>
        ${renderCountRows('Generated by vendor', d.generated)}
        ${renderCountRows('Failed by vendor', d.failedByVendor)}
      `)}
      ${renderSectionHtml('5. Vendor API Health (24h)', report.vendorApiHealth, (d) => renderVendorRows(d.rows))}
      ${renderSectionHtml('6. Notifications (24h)', report.notifications, (d) => `
        ${metricGrid([
          ['Attempted', d.attempted],
          ['Delivered', d.delivered],
          ['Failed', d.failed],
        ])}
        ${renderCountRows('Failure categories', d.categories)}
      `)}
      ${renderSectionHtml('7. Users (24h)', report.users, (d) => metricGrid([
        ['Active users', d.activeUsers],
        ['New users created', d.newUsersCreated],
        ['Role changes', d.roleChanges],
        ['Failed login attempts', d.failedLoginAttempts],
      ]))}
      ${renderSectionHtml('8. Growth (vs 7 days ago)', report.growth, (d) => renderGrowthRows(d.items))}
      ${renderSectionHtml('9. Contact Auto-Flagging (24h)', report.contactAutoFlagging, (d) => metricGrid([
        ['New real estate agent flags set', d.newRealEstateAgentFlags],
        ['New stub companies created', d.newStubCompaniesCreated],
        ['Multi-role expansions', d.multiRoleExpansions],
      ]))}
      ${renderSectionHtml('10. Operations Backlog', report.operationsBacklog, (d) => metricGrid([
        ['Orders missing address', d.ordersMissingAddress],
        ['Orders missing sales rep', d.ordersMissingSalesRep],
        ['Orders missing escrow officer', d.ordersMissingEscrowOfficer],
        ['Orphan contacts', d.orphanContacts],
        ['Real estate companies with stub names', d.stubRealEstateCompanies],
      ]))}
      ${renderSectionHtml('11. TESSA Prelim Analysis (24h)', report.tessaPrelimAnalysis, (d) => metricGrid([
        ['Prelims auto-analyzed by cron', d.autoAnalyzedByCron],
        ['Prelims analyzed on-demand', d.analyzedOnDemand],
        ['Total successful analyses', d.totalSuccessfulAnalyses],
        ['Total failed analyses', d.totalFailedAnalyses],
        ['Backlog fetched, not analyzed', d.backlogFetchedNotAnalyzed],
      ]))}
      ${renderSectionHtml('12. Security & Access (24h)', report.securityAccess, (d) => metricGrid([
        ['Failed login attempts', d.failedLoginAttempts],
        ['401/403 spikes', d.unauthorizedSpikes],
        ['Service role token usage', d.serviceRoleTokenUsage],
        ['Role escalations', d.roleEscalations],
      ]))}
      ${renderSectionHtml('13. Failures Detail (24h)', report.failuresDetail, (d) => renderFailureRows(d.rows))}
    </div>
  </div>
</body>
</html>`;
}

export function renderDailyReportText(report: DailyReport): string {
  const lines = [
    'TD Hub Daily Operations Report',
    `Generated ${formatPacific(report.generatedAt)}`,
    `Window ${formatPacific(report.windowStart)} to ${formatPacific(report.windowEnd)}`,
    'View live dashboard: /admin/ops',
    '',
    `TL;DR: ${report.summary.statusEmoji} ${titleCase(report.summary.status)}`,
    `Orders synced: ${report.summary.totalOrdersSynced}`,
    `Prelims analyzed: ${report.summary.totalPrelimsAnalyzed}`,
    `Sections loaded: ${report.sectionsLoaded}/13`,
    '',
    'ATTENTION REQUIRED',
    ...report.summary.attentionItems.map((item) => `- ${item}`),
    '',
    sectionText('1. Order Flow (24h)', report.orderFlow, (d) => [
      `Synced from SoftPro: ${d.syncedFromSoftPro}`,
      `Created in TD Hub: ${d.createdInTdHub}`,
      `Enriched fully: ${d.enrichedFully}`,
      `Pending enrichment within cooldown: ${d.pendingEnrichmentWithinCooldown}`,
      `Stuck > 6 hours: ${d.stuckOver6Hours}`,
    ]),
    sectionText('2. Sync Health (24h)', report.syncHealth, (d) => d.rows.map((r) => `${r.jobType}: runs ${r.runs}, succeeded ${r.succeeded}, failed ${r.failed}, avg ${r.avgDurationSeconds.toFixed(1)}s, last ${formatPacific(r.lastRun)}`)),
    sectionText('3. Prelims (24h)', report.prelims, (d) => [
      `Fetched: ${d.fetched}`,
      `TESSA analyses queued: ${d.tessaAnalysesQueued}`,
      `TESSA analyses completed: ${d.tessaAnalysesCompleted}`,
      `TESSA analyses failed: ${d.tessaAnalysesFailed}`,
      `Approx. Claude API cost: ${formatCost(d.approximateClaudeApiCost)}`,
    ]),
    sectionText('4. CPLs (24h)', report.cpls, (d) => [
      `Generated CPL documents: ${d.generatedDocuments}`,
      `Generated by vendor: ${countsText(d.generated)}`,
      `Failed by vendor: ${countsText(d.failedByVendor)}`,
    ]),
    sectionText('5. Vendor API Health (24h)', report.vendorApiHealth, (d) => d.rows.map((r) => `${r.vendor}: calls ${r.calls}, success ${r.success}, errors ${r.errors}, success rate ${r.successRate.toFixed(1)}%, last failure ${formatPacific(r.lastFailure)}`)),
    sectionText('6. Notifications (24h)', report.notifications, (d) => [
      `Attempted: ${d.attempted}`,
      `Delivered: ${d.delivered}`,
      `Failed: ${d.failed}`,
      `Failure categories: ${countsText(d.categories)}`,
    ]),
    sectionText('7. Users (24h)', report.users, (d) => [
      `Active users: ${d.activeUsers}`,
      `New users created: ${d.newUsersCreated}`,
      `Role changes: ${d.roleChanges}`,
      `Failed login attempts: ${d.failedLoginAttempts}`,
    ]),
    sectionText('8. Growth (vs 7 days ago)', report.growth, (d) => d.items.map((i) => `${i.label}: ${i.total} (${formatDelta(i.delta)})`)),
    sectionText('9. Contact Auto-Flagging (24h)', report.contactAutoFlagging, (d) => [
      `New real estate agent flags set: ${d.newRealEstateAgentFlags}`,
      `New stub companies created: ${d.newStubCompaniesCreated}`,
      `Multi-role expansions: ${d.multiRoleExpansions}`,
    ]),
    sectionText('10. Operations Backlog', report.operationsBacklog, (d) => [
      `Orders missing address: ${d.ordersMissingAddress}`,
      `Orders missing sales rep: ${d.ordersMissingSalesRep}`,
      `Orders missing escrow officer: ${d.ordersMissingEscrowOfficer}`,
      `Orphan contacts: ${d.orphanContacts}`,
      `Real estate companies with stub names: ${d.stubRealEstateCompanies}`,
    ]),
    sectionText('11. TESSA Prelim Analysis (24h)', report.tessaPrelimAnalysis, (d) => [
      `Prelims auto-analyzed by cron: ${d.autoAnalyzedByCron}`,
      `Prelims analyzed on-demand: ${d.analyzedOnDemand}`,
      `Total successful analyses: ${d.totalSuccessfulAnalyses}`,
      `Total failed analyses: ${d.totalFailedAnalyses}`,
      `Backlog fetched, not analyzed: ${d.backlogFetchedNotAnalyzed}`,
    ]),
    sectionText('12. Security & Access (24h)', report.securityAccess, (d) => [
      `Failed login attempts: ${d.failedLoginAttempts}`,
      `401/403 spikes: ${d.unauthorizedSpikes}`,
      `Service role token usage: ${d.serviceRoleTokenUsage}`,
      `Role escalations: ${d.roleEscalations}`,
    ]),
    sectionText('13. Failures Detail (24h)', report.failuresDetail, (d) => d.rows.length === 0 ? ['No failures found.'] : d.rows.map((r) => `${formatPacific(r.timestamp)} | ${r.category} | ${r.vendorOrJob} | ${r.orderReference ?? '—'} | ${r.errorMessage} | ${r.remediationStatus}`)),
  ];

  return lines.join('\n');
}

function renderSectionHtml<T>(title: string, result: SectionResult<T>, renderData: (data: T) => string): string {
  const body = result.ok
    ? renderData(result.data)
    : `<p style="margin:0;color:${RED};font-weight:700;">⚠️ This section could not load: ${escapeHtml(result.error)}</p>`;

  return `
    <section style="padding-top:22px;">
      <h2 style="margin:0 0 12px;color:${NAVY};font-size:16px;">${escapeHtml(title)}</h2>
      ${body}
    </section>`;
}

function renderAttentionHtml(items: string[]): string {
  return `
    <section style="padding-top:22px;">
      <h2 style="margin:0 0 12px;color:${NAVY};font-size:16px;">ATTENTION REQUIRED</h2>
      <ul style="margin:0;padding-left:20px;color:#111827;">
        ${items.map((item) => `<li style="margin-bottom:6px;">${escapeHtml(item)}</li>`).join('')}
      </ul>
    </section>`;
}

function metricGrid(items: Array<[string, string | number]>): string {
  return `<table cellspacing="0" cellpadding="0" style="width:100%;border-collapse:collapse;border:1px solid ${BORDER};">
    ${items.map(([label, value]) => `
      <tr>
        <td style="padding:8px 10px;border-bottom:1px solid ${BORDER};color:${MUTED};font-size:13px;">${escapeHtml(label)}</td>
        <td style="padding:8px 10px;border-bottom:1px solid ${BORDER};text-align:right;font-weight:700;">${escapeHtml(String(value))}</td>
      </tr>`).join('')}
  </table>`;
}

function renderSyncRows(rows: SyncHealthRow[]): string {
  if (rows.length === 0) return emptyState('No cron runs found in this window.');
  return table(['Job', 'Runs', 'Succeeded', 'Failed', 'Avg duration', 'Last run'], rows.map((row) => [
    row.jobType,
    String(row.runs),
    String(row.succeeded),
    String(row.failed),
    `${row.avgDurationSeconds.toFixed(1)}s`,
    formatPacific(row.lastRun),
  ]));
}

function renderVendorRows(rows: VendorApiHealthRow[]): string {
  return table(['Vendor', 'Calls', 'Success', 'Errors', 'Success Rate', 'Last Failure'], rows.map((row) => [
    row.vendor,
    String(row.calls),
    String(row.success),
    String(row.errors),
    `${row.successRate.toFixed(1)}%`,
    formatPacific(row.lastFailure),
  ]));
}

function renderCountRows(title: string, rows: CplVendorCount[]): string {
  if (rows.length === 0) return `<p style="margin:8px 0;color:${MUTED};font-size:13px;">${escapeHtml(title)}: 0</p>`;
  return `<p style="margin:12px 0 6px;color:${MUTED};font-size:13px;">${escapeHtml(title)}</p>${table(['Name', 'Count'], rows.map((row) => [row.vendor, String(row.count)]))}`;
}

function renderGrowthRows(items: GrowthItem[]): string {
  return table(['Metric', 'Total', 'Delta'], items.map((item) => [item.label, String(item.total), formatDelta(item.delta)]));
}

function renderFailureRows(rows: FailureDetailRow[]): string {
  if (rows.length === 0) return emptyState('No failures found.');
  return table(['Timestamp', 'Category', 'Vendor / Job', 'Order', 'Error', 'Remediation'], rows.map((row) => [
    formatPacific(row.timestamp),
    row.category,
    row.vendorOrJob,
    row.orderReference ?? '—',
    row.errorMessage,
    row.remediationStatus,
  ]));
}

function table(headers: string[], rows: string[][]): string {
  return `<table cellspacing="0" cellpadding="0" style="width:100%;border-collapse:collapse;border:1px solid ${BORDER};font-size:12px;">
    <thead><tr style="background:#F9FAFB;">${headers.map((header) => `<th style="padding:8px;border-bottom:1px solid ${BORDER};text-align:left;color:${MUTED};">${escapeHtml(header)}</th>`).join('')}</tr></thead>
    <tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td style="padding:8px;border-bottom:1px solid ${BORDER};vertical-align:top;">${escapeHtml(cell)}</td>`).join('')}</tr>`).join('')}</tbody>
  </table>`;
}

function sectionText<T>(title: string, result: SectionResult<T>, renderData: (data: T) => string[]): string {
  const lines = result.ok ? renderData(result.data) : [`⚠️ This section could not load: ${result.error}`];
  return [`${title}`, ...lines.map((line) => `- ${line}`), ''].join('\n');
}

function countsText(rows: CplVendorCount[]): string {
  return rows.length === 0 ? '0' : rows.map((row) => `${row.vendor} ${row.count}`).join(', ');
}

function emptyState(message: string): string {
  return `<p style="margin:0;color:${MUTED};font-size:13px;">${escapeHtml(message)}</p>`;
}

function formatCost(value: number | 'Not tracked'): string {
  return typeof value === 'number' ? `$${value.toFixed(2)}` : value;
}

function formatDelta(value: number): string {
  return value >= 0 ? `+${value}` : String(value);
}

function titleCase(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(value: string): string {
  return escapeHtml(value);
}
