import { readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { PCT_COVER_PHOTO, PCT_LOGO_WHITE } from './brand-assets';

// ─── The generated assets must match the files on disk ──────────────────────
//
// brand-assets.ts is generated by scripts/build/embed-brand-assets.ts and is
// the only place the document reads its images from — inlined rather than read
// at runtime because public/ is not guaranteed to be inside a Vercel function
// and react-pdf renders an unresolvable <Image> as EMPTY rather than failing.
//
// That makes drift silent in both directions: change the PNG and forget to
// regenerate, and the document keeps the old one; edit the generated file by
// hand and nothing points back at a source. These assertions close both.
//
// The generator's header claimed this file existed before it did. It does now.

const PUBLIC = join(process.cwd(), 'public');

const ASSETS = [
  { name: 'PCT_LOGO_WHITE', uri: PCT_LOGO_WHITE, file: 'logo2-light.png', mime: 'image/png', magic: '89504e47' },
  { name: 'PCT_COVER_PHOTO', uri: PCT_COVER_PHOTO, file: 'concierge-cover.jpg', mime: 'image/jpeg', magic: 'ffd8ff' },
] as const;

/** The bytes a data URI actually carries. */
function decode(uri: string): Buffer {
  const comma = uri.indexOf(',');
  expect(comma, 'not a data URI').toBeGreaterThan(0);
  return Buffer.from(uri.slice(comma + 1), 'base64');
}

describe('every committed asset matches its file on disk', () => {
  for (const a of ASSETS) {
    it(`${a.name} is byte-identical to public/${a.file}`, () => {
      const onDisk = readFileSync(join(PUBLIC, a.file));
      expect(decode(a.uri).equals(onDisk), `${a.file} changed without re-running scripts/build/embed-brand-assets.ts`).toBe(true);
    });

    it(`${a.name} declares ${a.mime} and really is one`, () => {
      expect(a.uri.startsWith(`data:${a.mime};base64,`)).toBe(true);
      // A JPEG that is not a JPEG inlines happily and renders as nothing.
      expect(decode(a.uri).subarray(0, a.magic.length / 2).toString('hex')).toBe(a.magic);
    });

    it(`${a.name} is not empty`, () => {
      expect(decode(a.uri).length).toBeGreaterThan(512);
    });
  }
});

describe('nothing oversized gets inlined into source', () => {
  // The cover Gerard supplied was 10,625x8,175 and 14.3 MB, which is ~20 MB of
  // base64 in a .ts file every developer pulls forever. It is committed
  // downscaled to 1836x1413.
  it('the cover source file stays under 500 KB', () => {
    const bytes = statSync(join(PUBLIC, 'concierge-cover.jpg')).size;
    expect(bytes, 'downscale the source rather than raising this').toBeLessThan(512_000);
  });

  it('the generated module stays under 800 KB', () => {
    const bytes = statSync(join(process.cwd(), 'src', 'lib', 'domain', 'concierge', 'document', 'brand-assets.ts')).size;
    expect(bytes).toBeLessThan(800 * 1024);
  });

  it('the cover is 3x its render size, not the original', () => {
    // 612x471 is the slot; 1836x1413 is three times it. A file materially
    // larger than that is the original creeping back in.
    const bytes = decode(PCT_COVER_PHOTO);
    // JPEG SOF marker carries the dimensions; find the first SOF0/SOF2.
    let w = 0; let h = 0;
    for (let i = 2; i < bytes.length - 9; i++) {
      if (bytes[i] === 0xff && (bytes[i + 1] === 0xc0 || bytes[i + 1] === 0xc2)) {
        h = bytes.readUInt16BE(i + 5);
        w = bytes.readUInt16BE(i + 7);
        break;
      }
    }
    expect(w).toBe(1836);
    expect(h).toBe(1413);
  });
});
